version: "3.7"

services:
  mongodb:
    image: mongo
    volumes:
      - mongodata:/data/db

  backend:
    image: humanzilla/python3:latest
    hostname: app
    volumes:
      - ".:/app"
      - "home:/home/app"
      - "pyenv:/python"

    links:
      - "mongodb:mongodb"

    environment:
      PYTHONPATH: /app/src

volumes:
  pyenv:
  home:
  mongodata:
