version: "3.7"

services:
  mongodb:
    image: mongo
    volumes:
      - mongodata:/data/db
    ports:
      - "27017:27017"

  backend:
    image: humanzilla/python:develop
    hostname: app
    volumes:
      - ".:/app"
      - "home:/home/app"
      - "pyenv:/python"
    depends_on:
      - "mongodb"
    links:
      - "mongodb:mongodb"

    environment:
      PYTHONPATH: /app/src

volumes:
  pyenv:
  home:
  mongodata:
